-- Ejecutar CONECTADO a la base centro_comunitario; no sobre postgres.
-- DDL: seis tablas relacionadas y restricciones integridad.
BEGIN; -- Inicia transacción para crear el esquema completo.
CREATE TABLE IF NOT EXISTS solicitantes ( -- Personas que solicitan una sala.
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Clave primaria.
 nombre VARCHAR(100) NOT NULL, -- Nombre obligatorio.
 correo VARCHAR(120) NOT NULL UNIQUE, -- Contacto único.
 CONSTRAINT chk_solicitante_nombre CHECK (length(trim(nombre)) > 0) -- Nombre no vacío.
);
CREATE TABLE IF NOT EXISTS salas ( -- Espacios físicos.
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID sala.
 nombre VARCHAR(80) NOT NULL UNIQUE, -- Identificación única.
 capacidad INTEGER NOT NULL CHECK (capacidad BETWEEN 1 AND 200), -- Aforo permitido.
 activa BOOLEAN NOT NULL DEFAULT TRUE -- Inhabilita sala sin eliminarla.
);
CREATE TABLE IF NOT EXISTS equipamientos ( -- Material que se presta junto a la sala.
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador.
 nombre VARCHAR(80) NOT NULL UNIQUE, -- Nombre único de equipo.
 stock INTEGER NOT NULL CHECK (stock >= 0) -- Stock nunca negativo.
);
CREATE TABLE IF NOT EXISTS estados_reserva ( -- Catálogo de estados.
 id INTEGER PRIMARY KEY, -- ID fijo para consulta simplificada.
 nombre VARCHAR(30) NOT NULL UNIQUE -- Activa o Cancelada.
);
CREATE TABLE IF NOT EXISTS reservas ( -- Registro de fecha, hora y solicitante.
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK reserva.
 solicitante_id INTEGER NOT NULL REFERENCES solicitantes(id), -- Relación 1:N personas/reservas.
 sala_id INTEGER NOT NULL REFERENCES salas(id), -- Relación 1:N salas/reservas.
 estado_id INTEGER NOT NULL REFERENCES estados_reserva(id), -- Relación 1:N estado/reservas.
 inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Hora local del ejercicio, sin TZ.
 fin TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Fin local del ejercicio.
 motivo VARCHAR(120) NOT NULL CHECK (length(trim(motivo)) > 0), -- Motivo requerido.
 participantes INTEGER NOT NULL CHECK (participantes >= 1), -- No puede reservar para cero personas.
 creada_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT LOCALTIMESTAMP, -- Auditoría básica.
 CONSTRAINT chk_fechas CHECK (fin > inicio), -- Restricción redundante de seguridad.
 CONSTRAINT chk_duracion CHECK (fin <= inicio + INTERVAL '4 hours') -- Máximo cuatro horas.
);
CREATE TABLE IF NOT EXISTS reserva_equipamientos ( -- Puente N:M entre reservas y equipamientos.
 reserva_id INTEGER NOT NULL REFERENCES reservas(id) ON DELETE RESTRICT, -- FK reserva.
 equipamiento_id INTEGER NOT NULL REFERENCES equipamientos(id) ON DELETE RESTRICT, -- FK equipo.
 cantidad INTEGER NOT NULL CHECK (cantidad > 0), -- Unidades solicitadas.
 PRIMARY KEY (reserva_id, equipamiento_id) -- Impide duplicado del mismo equipo por reserva.
);
CREATE INDEX IF NOT EXISTS ix_reservas_sala_intervalo ON reservas(sala_id,inicio,fin); -- Acelera solapes.
CREATE INDEX IF NOT EXISTS ix_reserva_equipos_equipo ON reserva_equipamientos(equipamiento_id); -- Acelera stock.
COMMIT; -- Guarda estructuras.
